version: '3'
services: 
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/local/app
    command: 'npm run dev'
  db:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
    command: 'mongod --auth'
volumes:
  mongo-db:
    driver: local